# Generated by Django 3.2 on 2022-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CON', 'Confirmed'), ('PEN', 'Awaiting Shipment'), ('SHIP', 'Shipped'), ('DEL', 'Closed'), ('CAN', 'Cancelled')], default='CON', max_length=10),
        ),
    ]
