# Generated by Django 3.2 on 2022-06-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='customer_email',
            new_name='email',
        ),
    ]
