# Generated by Django 3.2 on 2022-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(choices=[(1.0, '1'), (2.0, '2'), (3.0, '3'), (4.0, '4'), (5.0, '5')], decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
